### PR TITLE
updates for copying config files and using loopkup cet lib

### PR DESCRIPTION
**Pull request by gianipez**
tagging @eflumerf

### CODE REVIEW

**Review by eflumerf — CHANGES_REQUESTED** [review]
Looked-up file path is not used (L651). Probably want to use a different variable, not FHICL_FILE_PATH. I would suggest MU2E_CALORIMETER_CONFIG_PATH to be perfectly clear; this variable can be set in the Spack package.py

**Review by eflumerf — APPROVED** [review]

**Comment by kutschke** [comment]
> Looked-up file path is not used (L651). Probably want to use a different variable, not FHICL_FILE_PATH. I would suggest MU2E_CALORIMETER_CONFIG_PATH to be perfectly clear; this variable can be set in the Spack package.py

Would list file be found correctly by FHICL_FILE_PATH?  Will this code run in Offline?

For Offline. we started we made a design decision years ago to avoid proliferation of run-time environment variables and limit them to FHICL_FILE_PATH and MU2E_SEARCH_PATH, which is just FHICL_FILE_PATH  plus /cvmfs/mu2e.opensciencegrid.org/DataFiles/ .  Our reason is that we don't want to have to audit many environment variables to make sure that they point at locations that contain files that are version controlled.

If this code will run in Offline,  and if MU2E_SEARCH_PATH will work, I request that you stick with the Offline design,  If it won't work we need to talk.

**Comment by kutschke** [comment]
I just updated the last para of the previous comment.

**Comment by eflumerf** [comment]
@kutschke This is TDAQ-only, the Offline should not have to worry about it. I don't think we can stuff the env var rabbit back in the hat over here 😭

**Pull request merged**
